services:
  neo4j:
    image: neo4j:latest
    volumes:
      - ./data/logs:/logs
      - ./data/config:/config
      - ./data/data:/data
      - ./data/plugins:/plugins
      - ./outputparser.cypher:/import/outputparser.cypher
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always