version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"   # Expose MongoDB on port 27017
    volumes:
      - mongodb_data:/data/db  # Persist MongoDB data

volumes:
  mongodb_data: