version: '3'

services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - "8086:8086"   # Exposes port 8086 to the host
    volumes:
      - influxdb_data:/var/lib/influxdb  # Persists InfluxDB data

volumes:
  influxdb_data: